### ISSUE TITLE
updateStateOnServer() caught exception:

### ISSUE THREAD

**Issue by achterberg** [autolog/LIFX_Controller#3]
These informational errors have been showing up in the log. These are all LIFX White 800 bulbs.

   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device Bedside Left
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device Bedside Left
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device Bedside Right
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device Bedside Right
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device Lamp
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device Lamp

**Comment by autolog** [comment]
Is there something specific triggering this? 
Are the lights still being controlled e.g. can you turn them on and off via the plugin?
What version of the plugin are you using?

I haven't got a LIFX White 880 bulb to test with but will try and resolve this for you. :)

**Comment by achterberg** [comment]
Seems like every time the plugin polls the lights, I have it set for 5 minutes. Also when you control the lights.
The lights still work, on, off dim.
v.6.0.11

It has been going on for a while (months?), doesn’t bother me since the lights still work, but it went away when I upgraded to Catalina, and is back when I upgraded this weekend to 10.15.7, don’t know if that has anything to do with it. Restarting the plugin doesn’t seem to help.

**Comment by autolog** [comment]
What version of the plugin are you using?

**Comment by achterberg** [comment]
v.6.0.11

sent from space

**Comment by autolog** [comment]
I have managed to reproduce the error by setting my LIFX A19+ bulbs to non-colour in the internal device definition on my development system. Now that I can reproduce it, I should be able to track it down and fix it. May take up to a week or so. :)

**Comment by achterberg** [comment]
﻿Perfect, no rush like I indicated before. 

sent from space



sent from space

**Comment by autolog** [comment]
Version 6.0.12 uploaded and available as a pre-release. Should fix the issue and also reveal the White level controls in the Indigo UI Device Details.

**Comment by achterberg** [comment]
Installed and no log messages after 5 minutes and the controls work, I’ll let it run today and let you know, but I think you fixed it.

**Comment by achterberg** [comment]
Seems to working; all day and no messages.

**Comment by blueatria** [comment]
I have mini whites that produce the same error. I have 6.0.12 and still the same error.
LIFX                            Starting  'TV 1' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 1'.
   LIFX                            Starting  'TV 2' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 2'.
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2


Only happens on startup of the plugin.

**Comment by blueatria** [comment]
Works no problem except for the errors at startup of the plugin
LIFX                            Starting  'TV 1' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 1'.
   LIFX                            Starting  'TV 2' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 2'.
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2


When I turn one of the lights on and dim up and down the following is in the log
 LIFX                            sent "TV 1" on with duration of 1.0 seconds
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            sent "TV 1" dim to 59 with duration of 1.0 seconds
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            sent "TV 1" brighten to 100 with duration of 1.0 seconds
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            sent "TV 1" off with duration of 1.0 seconds
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1

The light dows turn on and dim correctly and turns off.

**Comment by autolog** [comment]
I have uploaded pre-release Version 6.0.15 which will hopefully sort the problem out!
Let me know if it does and then I will release it to the Indigo Plugin Store.

**Comment by blueatria** [comment]
Just tried out the update. So the exception is gone but it seems to be having trouble talking to the downlight I have here is the log entry
   Starting plugin "LIFX 6.0.15" (pid 51219)
   LIFX                            
============================================== Initialising LIFX Controller Plugin ===============================================
Plugin Name:                    LIFX
Plugin Version:                 6.0.15
Plugin ID:                      com.autologplugin.indigoplugin.lifxcontroller
Indigo Version:                 7.5.0
Indigo API Version:             2.4
Python Version:                 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Mac OS Version:                 10.15.7
==================================================================================================================================

   LIFX                            Logging to Indigo Event Log at the 'Info' level
   LIFX                            Logging to LIFX Plugin Log at the 'Info' level
   Started plugin "LIFX 6.0.15"
   LIFX                            'LIFX Controller' giving Discovery an opportunity to complete . . .
   LIFX                            LIFX device discovery starting (this can take up to 60 seconds) . . .
   LIFX Warning                    LIFXLAN [discover_devices] discovered a LIFX Switch device with product code: '70'. Device's MAC is 'd0:73:d5:5a:89:15' and IP Address is '192.168.86.163'. LIFX switch devices are not supported by the plugin
   LIFX                            

LIFX device discovery has completed. 6 LIFX device(s) have been discovered as follows:

Start of discovered LIFX devices list ---->
  'Beam'        [d0:73:d5:27:d8:bf] at 192.168.86.20
  'Dining Room' [d0:73:d5:25:9e:23] at 192.168.86.84
  'Kitchen'     [d0:73:d5:28:65:35] at 192.168.86.175
  'Lounge Room' [d0:73:d5:28:53:ad] at 192.168.86.122
  'TV 1'        [d0:73:d5:32:5f:82] at 192.168.86.252
  'TV 2'        [d0:73:d5:32:5d:05] at 192.168.86.73
<---- End of discovered LIFX devices list.

   LIFX                            . . . 'LIFX Controller' initialization now completed.
   LIFX                            Starting  'Beam' . . . 
   LIFX                            . . . Started 'LIFX LIFX Beam' device: 'Beam'.
   LIFX                            Starting  'Dining Room' . . . 
   LIFX                            . . . Started 'LIFX LIFX A19' device: 'Dining Room'.
   LIFX                            Starting  'Kitchen' . . . 
   LIFX                            . . . Started 'LIFX LIFX A19' device: 'Kitchen'.
   LIFX                            Starting  'Lounge Room' . . . 
   LIFX                            . . . Started 'LIFX LIFX A19' device: 'Lounge Room'.
   LIFX                            Starting  'Terrace 1' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Terrace 1' with MAC address 'd0:73:d5:27:b3:03' at IP address '192.168.86.133 . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 1' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 1' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 1' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 1' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 1' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Terrace 1' with MAC address 'd0:73:d5:27:b3:03' at IP address '192.168.86.133
   LIFX                            Starting  'Terrace 2' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Terrace 2' with MAC address 'd0:73:d5:27:29:99' at IP address '192.168.86.215 . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 2' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 2' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 2' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 2' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 2' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Terrace 2' with MAC address 'd0:73:d5:27:29:99' at IP address '192.168.86.215
   LIFX                            Starting  'Terrace 3' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Terrace 3' with MAC address 'd0:73:d5:27:bb:ea' at IP address '192.168.86.180 . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 3' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 3' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 3' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 3' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 3' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Terrace 3' with MAC address 'd0:73:d5:27:bb:ea' at IP address '192.168.86.180
   LIFX                            Starting  'Terrace 4' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Terrace 4' with MAC address 'd0:73:d5:27:af:9d' at IP address '192.168.86.96 . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   Z-Wave                          received "Pool Pump" energy total to 6661.514 kWh
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   Z-Wave                          received "UPS 2" energy total to 4596.448 kWh
   Z-Wave                          received "UPS 2" power load to 260.605 W
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Terrace 4' with MAC address 'd0:73:d5:27:af:9d' at IP address '192.168.86.96
   LIFX                            Starting  'TV 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 1'.
   LIFX                            Starting  'TV 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 2'.

The mac addresses and ip addresses are correct. I can control the lights from the lifx app.

Not sure what is going on here. I have turned power off for the four lights and back on to reboot them but same result

**Comment by autolog** [comment]
I have just tested with my downlights and they are working OK.
Normally that error would indicate some sort of network problem, but as you say it is working OK from the App.

What is interesting is that the discovery hasn't found your Terrace downlights.

If you haven't already, restart the plugin to see if that clears it?

Failing that, revert to the previous version to see if that fixes it.
